name: Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    env:
      latest_php: 8.3

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [
          '5.5', '5.6',
          '7.0', '7.1', '7.2', '7.3', '7.4',
          '8.0', '8.1', '8.2', '8.3', '8.4'
        ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --quiet --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Migrate phpunit XML configuration
        run: vendor/bin/phpunit --migrate-configuration || true

      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
        if: matrix.php == env.latest_php
